### ISSUE TITLE
Not filtering degenerate data correctly. 

### ISSUE THREAD

**Issue by JamieTD** [DesignEngrLab/MIConvexHull#12]
Found that the FindInitialPoints() method in the ConvexHullAlgorithm.Initialize script, at line 500, was not correctly throwing an error when a degenerate set of data was found. We found that this was due to the conditional if the if statement " && IsLifted"

**Comment by micampbell** [comment]
That is correct. I'm a little bashful about that. Is it a hack? Well, most of the recent problems people have had point to problems with Delaunay triangulation on uniformly spaced points. This term "IsLifted" is intended to catch cases when an additional dimension is added for Delaunay and Voronoi. Instead of being degenerate and throwing an error, we deal with it and do an arbitrary initial triangulation of the simplex. Make sense? Do this answer your question, or does your problem persist?
