### ISSUE TITLE
Convex Hull result is not shown correctly

### ISSUE THREAD

**Issue by xxxdomi** [DesignEngrLab/MIConvexHull#49]
Hello! :-)

Currently, I am making some experiments with your convex hull lib. 

When I try your eifelturm sample, this works perfectly, as you can seen in the following pictures.

Orig
![image](https://user-images.githubusercontent.com/37882573/209310479-c63a3050-2c4b-402d-ac4a-04e61ac0f07d.png)

Convex Hull
![image](https://user-images.githubusercontent.com/37882573/209310219-618eed77-98b6-47a8-85e1-7cfac50d72db.png)

If I try to simplify another CAD like this one (monkey head) below, it does not output the result that i am expect. What do you think - is it a problem of your algorithm, or is this probem somewhere else?

Orig:
![image](https://user-images.githubusercontent.com/37882573/209310610-5684539e-46dd-4328-99aa-eed8c7af5d30.png)

Convex Hull

![image](https://user-images.githubusercontent.com/37882573/209310141-cde7042c-96f8-42bd-a7d2-24a39565c6e2.png)

Thanks in adavance,
Dominik

[suzanne.zip](https://github.com/DesignEngrLab/MIConvexHull/files/10294036/suzanne.zip)

**Comment by massonib** [comment]
Dominik, that is the correct convex hull. The issue is with your tessellation/viewer dropping triangles and perhaps not seeing it at the correct orientation. Here is an image of your part with the convex hull wrapped around it, created using TVLG (https://github.com/DesignEngrLab/TVGL), I should also mention that your model is not a proper tessellation and may cause some issues in TVGL and other such model tessellation manipulators.

![image](https://user-images.githubusercontent.com/12925670/209400364-ead48391-0fd2-47e7-9c43-61850042982c.png)

![image](https://user-images.githubusercontent.com/12925670/209400782-d48769ac-c2ee-4e48-8719-25d91aa63edc.png)

**Comment by micampbell** [comment]
Thanks @massonib. The tessellation error should not affect the accuracy of the convex hull since convex hull only uses vertex information.
